version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: aiagent-postgres
    environment:
      POSTGRES_DB: aiagent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aiagent-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aiagent-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=aiagent;Username=postgres;Password=postgres
      - JWT__Secret=h2Ue9xL4qz3WmV7KpR6aY1fTnC0oX8BdJrEsMiZtUvGbQ5Nc
      - JWT__Issuer=AiAgentApi
      - JWT__Audience=AiAgentApp
      - JWT__ExpiryInDays=7
      - Bold__ApiKey=ydgILNf8rAjC2qsY-kTwUg
      - Bold__BaseUrl=https://api.bold.co
      - Bold__SuccessUrl=http://localhost:3000/purchase?payment=success
      - Bold__FailureUrl=http://localhost:3000/purchase?payment=failed
      - Email__Host=smtp.gmail.com
      - Email__Port=587
      - Email__Username=vamv86@gmail.com
      - Email__Password=xsak aqgl iadv ruue
      - Email__FromName=AI Agent
      - Email__FromEmail=vamv86@gmail.com
      - N8N__BaseUrl=http://localhost:5678
      - N8N__ApiKey=your-n8n-api-key
      - App__BaseUrl=http://localhost:5000
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    networks:
      - aiagent-network
    volumes:
      - ./backend:/app
    command: ["dotnet", "AiAgentApi.dll"]

volumes:
  postgres_data:

networks:
  aiagent-network:
    driver: bridge
