name: Build and Push Frontend to GHCR

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/aiagent-frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository_owner }}/aiagent-frontend:latest

      - name: Trigger Portainer webhook
        run: curl -X POST https://devportainer.avainnova.com.co/api/webhooks/<tu-webhook-id>
